---
# This playbook deploys the whole application stack in this site.

- name: Provision Instance from TOWER with ansible
  hosts: localhost
  connection: local

  roles:
    - { role: openstack-auth-ansible, tags: auth-ansible }

  tasks:
  - name: Create {{ item }} Instances
    include_role:
       name: openstack-instance
       vars_from: "{{ item }}.yaml"
    with_items:
      - web
      - was
      - db

  - name: debug newnodes
    debug:
      var: newnodes

  - name: Waiting for role includes to complete
    async_status:
      jid={{ newnodes['results'][0]['ansible_job_id'] }}
    register: my_async_job_status
    until: my_async_job_status.finished
    retries: 20

  - name: gather instance facts
    os_server_facts:
      auth: "{{ os_auth }}"
      server: db*
    register: result

  - name: debug
    debug:
      var: openstack_servers

  - name: Wait for Last Instance to be available
    wait_for:
      host: "{{ openstack_servers[0]['accessIPv4'] }}"
      port: 22
      search_regex: OpenSSH
      timeout: 300
    delegate_to: "{{ inventory_hostname }}"


#  - name: add instance
#    add_host:
#      name: "{{ instance_name }}{{ count }}"
#
#  - name: gather instance facts
#    os_server_facts:
#      auth: "{{ os_auth }}"
#      server: web*
#
#  - name: Wait for "{{ instance_name }}" to be available
#    wait_for:
#      host: "{{ inventory_hostname }}"
#      port: 22
#      search_regex: OpenSSH
#      timeout: 180
#    delegate_to: "{{ inventory_hostname }}"
