---
# tasks file for osp-network
#  - os_network:
#      auth: "{{ os_auth }}"
#      state: present
#      name: ext_network
#      external: true
#      provider_network_type: flat
#      provider_physical_network: physnet1
#  - os_subnet:
#      auth: "{{ os_auth }}"
#      state: present
#      network_name: ext_network
#      name: external_subnet
#      cidr: 192.168.122.0/24
#      allocation_pool_start: 192.168.122.110
#      allocation_pool_end: 192.168.122.120
#      gateway_ip: 192.168.122.1
#      dns_nameservers:
#         - 8.8.8.7
#         - 8.8.8.8

- name: Create Network by Ansible
  os_network:
    auth: "{{ os_auth }}"
    state: present
    interface: public
    name: automated_network
    external: false

#- name: Create Subnet by Ansible  
#  os_subnet:
#    auth: "{{ os_auth }}"
#    state: present
#    network_name: automated_network
#    name: automated_subnet
#    cidr: 10.10.10.0/24
#    dns_nameservers:
#       - 8.8.8.7
#       - 8.8.8.8

#- os_router:
#    auth: "{{ os_auth }}"
#    state: present
#    name: auto_router1
#    network: ext_network
#    external_fixed_ips:
#      - subnet: external_subnet
#    interfaces:
#      - automated_subnet
