---
# tasks file for openstack-securitygroup

- name: Create Security_Group_Was
  os_security_group:
    auth: "{{ os_auth }}"
    state: present
    name: was_servers
    description: ports_open

- name: Create Security_Group_Rule_Was
  os_security_group_rule:
    auth: "{{ os_auth }}"
    security_group: was_servers 
    protocol: tcp
    port_range_min: "{{ item.port }}"
    port_range_max: "{{ item.port }}" 
    remote_ip_prefix: "{{ item.ip_prefix }}"
  with_items:
    - { port: '8080', ip_prefix: '0.0.0.0/0' }
    - { port: '22', ip_prefix: '0.0.0.0/0' }
    - { port: '8009', ip_prefix: '0.0.0.0/0' }

- name: Create Security_Group_Rule_Was_Egress
  os_security_group_rule:
    auth: "{{ os_auth }}"
    security_group: was_servers 
    protocol: tcp
    direction: egress
    remote_ip_prefix: 0.0.0.0/0
   
- name: Create Security_Group_Web
  os_security_group:
    auth: "{{ os_auth }}"
    state: present
    name: web_servers
    description: ports_open

- name: Create Security_Group_Rule_Web
  os_security_group_rule:
    auth: "{{ os_auth }}"
    security_group: web_servers 
    protocol: tcp
    port_range_min: "{{ item.port }}"
    port_range_max: "{{ item.port }}" 
    remote_ip_prefix: "{{ item.ip_prefix }}"
  with_items:
    - { port: '80', ip_prefix: '0.0.0.0/0' }
    - { port: '443', ip_prefix: '0.0.0.0/0' }
    - { port: '22', ip_prefix: '0.0.0.0/0' }

- name: Create Security_Group_Rule_Web_Egress
  os_security_group_rule:
    auth: "{{ os_auth }}"
    security_group: web_servers
    protocol: tcp
    direction: egress
    remote_ip_prefix: 0.0.0.0/0

- name: Create Security_Group_Web_ICMP
  os_security_group_rule:
    auth: "{{ os_auth }}"
    security_group: web_servers
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0
      
- name: Create Security_Group_DB
  os_security_group:
    auth: "{{ os_auth }}"
    state: present
    name: db_servers
    description: ports_open

- name: Create Security_Group_Rule_DB
  os_security_group_rule:
    auth: "{{ os_auth }}"
    security_group: db_servers
    protocol: tcp
    port_range_min: "{{ item.port }}"
    port_range_max: "{{ item.port }}" 
    remote_ip_prefix: "{{ item.ip_prefix }}"
  with_items:
    - { port: '3306', ip_prefix: '0.0.0.0/0' }
    - { port: '22', ip_prefix: '0.0.0.0/0' }

- name: Create Security_Group_Rule_DB_Egress
  os_security_group_rule:
    auth: "{{ os_auth }}"
    security_group: db_servers
    protocol: tcp
    direction: egress
    remote_ip_prefix: 0.0.0.0/0
