---
# tasks file for openstack-instance
- debug:
    var: floating_answer

- name: Create a server instance
  os_server:
    auth: "{{ os_auth }}"
    name: "{{ instance_name }}{{ item }}"
    image: wwd_rhel
    meta: "group={{ group }},deployment_name={{ deployment }}"
    flavor: m2.small_generated_by_ansible
    security_groups: "{{ security_group_name }}"
    auto_ip: "{{ floating_answer }}"
    key_name: ansible_ssh
    wait: yes
    nics:
    - net-name: "{{ vm_nic }}"
  register: newnodes
  async: 120
  poll: 0
  with_sequence: start=1 end="{{ count }}"

- name: add instance
  add_host:
    name: "{{ instance_name }}{{ count }}"

- name: gather instance facts
  os_server_facts:
    auth: "{{ os_auth }}"
    server: "{{ instance_name }}*"
  register: result

#- name: debug
#  debug:
#    var: openstack_servers[0]
#
#- name: Wait for "{{ instance_name }}" to be available
#  wait_for:
#    host: "{{ openstack_servers[0]['accessIPv4'] }}"
#    port: 22
#    search_regex: OpenSSH
#    timeout: 180
#  delegate_to: "{{ inventory_hostname }}"
