---
# tasks file for openstack-instance
- debug:
    var: floating_answer

- name: Create a server instance
  os_server:
    auth: "{{ os_auth }}"
    name: "{{ instance_name }}_{{ item }}"
    image: wwd_rhel
    meta: "group={{ group }},deployment_name={{ deployment }}"
    flavor: m2.small_generated_by_ansible
    security_groups: "{{ security_group_name }}"
    auto_ip: "{{ floating_answer }}"
    key_name: ansible_ssh
    wait: yes
    nics:
    - net-name: "{{ vm_nic }}"
  register: newnodes
  with_sequence: start=1 end="{{ count }}"

#- add_host: name={{ item.server.public_v4 }}
#    groups="{{ group }}"
#    ansible_user=root
#    instance_name={{ item.server.name }}
#  with_items: "{{ newnodes.results }}"
#
#- name: "Wait for SSH banners"
#  local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=5
#  become: False
#
#- name: install apps
#  apt: name={{ item }} update_cache=yes state=latest
#  with_items:
#    - htop
#    - git
#
#- name: Pause play to interact with the servers
#  pause: prompt="Playbook paused... hit <enter> to continue or <ctrl-c a> to abort"



#- name: Wait for "{{ instance_name }}" to be available
#  wait_for:
#    host: "{{ instancefloatingip.floating_ip.floating_ip_address }}"
#    port: 22
#    search_regex: OpenSSH
#    timeout: 180
#  delegate_to: "{{ inventory_hostname }}"
